name: Build Release Candidate
on:
  push:
    branches:
      - main
      - 'issue/11-cd_*' # TODO 삭제.
jobs:
  build:
    name: Build Release Candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Load CI cache.
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/**
            .gradle/**
          key: ci-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build Release Candidate.
        run: |
          touch ./local.properties
          ./gradlew clean assembleDebug -x :app:assembleDebug --continue
      - name: Create Release Candidate.
        run: |
          git tag "build/${{ github.RUN_NUMBER }}"
          git push origin "build/${{ github.RUN_NUMBER }}"
          gh release create "build/${{ github.RUN_NUMBER }}" -t "Release Candidate #${{ github.RUN_NUMBER }}" ./*/build/outputs/aar/*.aar
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
