name: CI
on:
  push:
    branches-ignore:
      - main
      - 'issue/11-cd_*' # TODO 삭제.
jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Load CI cache.
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/**
            .gradle/**
          key: ci-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Prepare unit test.
        run: |
          touch ./local.properties
          ./gradlew clean
          mkdir -p ./build/reports
      - name: Run unit test.
        run: |
          ./gradlew testDebugUnitTest --continue --rerun-tasks
          tree > ./build/reports/tree.txt
      - name: Prepare report artifact.
        run: |
          cp -r ./.github/workflows/ci/hosting/* ./build/reports/
      - if: success() || failure()
        name: Upload test report artifact.
        uses: actions/upload-artifact@v4
        with:
          name: android-library_ci_report_${{ github.run_number }}
          path: ./build/reports
          if-no-files-found: warn
