name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Run Unit Test
        run: |
          ./gradlew test --continue --rerun-tasks
