name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Load CI cache.
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/**
            .gradle/**
          key: ci-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run unit test.
        run: ./gradlew clean testDebugUnitTest --continue --rerun-tasks
      - name: Prepare report upload.
        run: |
          pwd
          cp -r ./.github/workflows/ci/hosting/* ./build/reports/publish/${{ github.run_number }}
          tree ./build
      - if: success() || failure()
        name: Upload test report artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "reports_${{ github.run_number }}"
          path: ./build/reports/publish/${{ github.run_number }}
          if-no-files-found: warn
