name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Run Unit Test
        run: |
          ./gradlew clean testDebugUnitTest --continue --rerun-tasks
      - if: success() || failure()
        uses: actions/upload-artifact@v4
        name: Upload test report
        with:
          name: "reports_${{ github.run_id }}"
          path: build/reports/tests
          if-no-files-found: warn
