name: Build Release Candidate
on:
  push:
    branches:
      - main
      - 'issue/11-cd' # TODO 삭제.
jobs:
  build:
    name: Build Release Candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Load CI cache.
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/**
            .gradle/**
          key: ci-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Prepare build.
        run: |
          ./gradlew clean
          mkdir -p ./build/reports
          git log --graph --pretty="%h -%d %s (%ar) <%an>" > ./build/reports/git-log.txt
      - name: Build Release Candidate.
        run: |
          ./gradlew assembleDebug --continue
          tree ./build > ./build/reports/tree.txt
      - name: Prepare report upload.
        run: |
          cp -r ./.github/workflows/ci/hosting/* ./build/reports/
      - if: success() || failure()
        name: Upload build artifact.
        uses: actions/upload-artifact@v4
        with:
          name: android-library_build_${{ github.run_number }}
          path: ./build
          if-no-files-found: warn
